### ISSUE TITLE
pastDays does not seem to work

### ISSUE THREAD

**Issue by andrew-ness** [borivojevic/moves-api-php#4]
Trying the example calls, this works:

``` php
$Moves->dailySummary(); # current day
```

But this does not:

``` php
$Moves->dailySummary(array('pastDays' => 3)); # past 3 days
```

It gives:
Fatal error: Uncaught exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response [status code] 400 [reason phrase] Bad Request [url] https://api.moves-app.com/api/1.1/user/summary/daily

**Comment by borivojevic** [comment]
I can not reproduce the problem.

Can you tell me version number of `moves-api-php` and `guzzle` you are using?

Also can you do `composer update` and then try running your example again?

Thanks :)

**Comment by andrew-ness** [comment]
Hi,

borivojevic/moves        1.1.0              PHP wrapper library for Moves API
guzzle/guzzle            v3.3.1             Guzzle is a PHP HTTP client library and framework for building RESTful web service clients

v3.3.1 came as a dependency from something else I'm using...I didn't realize it was a year old.  I just tried by loading only 1.1.0 of your API and guzzle v3.8.1 and the multiple day summary does work, so it seems that there was a compatibility issue with older versions of guzzle.  May be best to require a more recent version of guzzle in your composer.json?

Anyway, I will try to resolve my version discrepancies (the other library specifies 3.3.*).
Thank you for your help!

Andrew
